### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by alfaqi** [veoquynhs/hardhat-nft-fcc#1]
Hello @veoquynhs!
I did my best to solve your issues, but your code makes me crazy :(
I don't know what the issue is or where the issue?
I think you are sharing version of your code that is not the same that you are using and having issue with.
I want help you and I need you to help me.

I have an idea, what about to start from scratch, just the package file.
then we move on to test unit.

let me know if you are ready.

**Comment by veoquynhs** [comment]
I realized that my hardhat.config.js had require("@nomiclabs/hardhat-ethers");, which is pretty redundant. So when I compiled the code with the package.json - which is similar to Patrick's Repo, it forced me to install hardhat-ethers, which might be incompatible with my program. So when I removed that line: require("@nomiclabs/hardhat-ethers"); and then recompiled and deployed, my program worked totally fine.

**Comment by alfaqi** [comment]
ok, well done.
